repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v16.0.0'  # Versión específica de clang-format
    hooks:
      - id: clang-format
        args:
          - --style=file  # Usa el archivo .clang-format para el estilo
        files: ^(src/|include/).*\.(c|h)$
